### ISSUE TITLE
bip32: why can't private ExtendedKey instances convert to `ExtendedPublicKeys` with `TryFrom`?

### ISSUE THREAD

**Issue by pezcore** [iqlusioninc/crates#1018]
It seems that only public `ExtendedKey` instances can be converted to `ExtendedPublicKey` instances with `TryFrom<ExtendedKey> for ExtendedPublicKey<K>`. Why is that? Shouldn't  `ExtendedPublicKey::try_from()` compute the public key even when the given `ExtendedKey` is private instead of returning `Err(Crypto)`, because this conversion is cheap, unambiguous, and convenient for the user?

[reference](https://github.com/iqlusioninc/crates/blob/8fce4d9e704cf52ec1942b2f29bdc406ab0ee0e7/bip32/src/extended_key/public_key.rs#L133)

**Comment by tony-iqlusion** [comment]
When the `secp256k1` feature is enabled (which it is by default), it could compute the public key from the private key, yes.

PRs accepted to add this, or I will get around to implementing it eventually.

**Comment by pezcore** [comment]
Resolved by #1021
