### ISSUE TITLE
Cannot clone a `SecretVec<u8>` as `u8` is not `CloneableSecret`

### ISSUE THREAD

**Issue by Kerollmops** [iqlusioninc/crates#1070]
There can't seem to be a way to clone a `SecretVec<u8>` because [`Clone` is only implemented on `Secret<Vec<S>> where S: CloneableSecret + Zeroize`](https://docs.rs/secrecy/latest/secrecy/trait.CloneableSecret.html#impl-CloneableSecret-for-Vec%3CS%3E) and obviously `u8` is not `CloneableSecret` [but is `Zeroize`](https://docs.rs/secrecy/latest/secrecy/trait.Zeroize.html#impl-Zeroize).

I think the right implementation should be `Secret<Vec<S>> where S: Zeroize` and avoid implying `CloneableSecret`, am I right?

**Comment by Sytten** [comment]
Also facing this issue, kinda of annoying...

**Comment by danewalton** [comment]
+1

**Comment by tony-iqlusion** [comment]
Closing in favor of #1233
