### ISSUE TITLE
secrecy: Secret.as_ref() ?

### ISSUE THREAD

**Issue by mpalmer** [iqlusioninc/crates#1183]
Would you be open to a PR that implemented a `Secret::as_ref()` method, that worked essentially the same as `Option::as_ref()`?  That is, something like:

```rust
fn as_ref<T>(&self) -> SecretRef<&T> {
  // ...
}
```

**Comment by fjarri** [comment]
If I'm not mistaken the point of not having `as_ref()` and having `expose_secret()` instead is to make it explicit that the secret is being exposed (while `as_ref()` can happen transparently when there's an `impl AsRef` parameter).

**Comment by mpalmer** [comment]
A `SecretRef` would still require a call to `expose_secret()` to actually expose the secret (just as a call to `Option::as_ref()` doesn't unwrap the value in the `Some`); the use case is to be able to create multiple refs to the same secret without needing to clone them everywhere and have duplicate owned values scattered about.

**Comment by fjarri** [comment]
Ah sorry, didn't notice the new type. What's the advantage over just having `&Secret<T>`?

**Comment by mpalmer** [comment]
There was definitely a reason why `&Secret<T>` didn't work in the situation I was in, but to be honest, it's been too long since I opened this so the context has been swapped out, and I can't identify exactly what it was I was working on to remind me.  I'll close this for now, and when/if I stumble over the problem again, I'll reopen with more context.
