### ISSUE TITLE
bip32: add a method to create `ExtendedPrivateKey` from `SigningKey`

### ISSUE THREAD

**Issue by fjarri** [iqlusioninc/crates#1185]
Currently the only way to create an `ExtendedPrivateKey` is to generate it from a seed. I would like to use `bip32` to derive child keys for DKG shares, where a signing key (or rather a share of one) has already been created by different means. Would you accept a PR that adds this functionality? Such a constructor would probably have to take an external chain code as well, since it'll have to be the same for all shares.

**Comment by tony-iqlusion** [comment]
@fjarri sure, that sounds fine to me
