### ISSUE TITLE
BIP39: Release candidate to match the others

### ISSUE THREAD

**Issue by dvdplm** [iqlusioninc/crates#1197]
The `bip39` crate depends  on a few other crates in the RustCrypto ecosystem that are currently close to release: `sha2`, `hmac` and `k256` (optionally). Any chance we can get a pre-release out for `bip39` to match the pre-release dependencies?

Thanks!

**Comment by tony-iqlusion** [comment]
I assume you mean `bip32` but sure, I can do that
