### ISSUE TITLE
Change in API?

### ISSUE THREAD

**Issue by damccull** [iqlusioninc/crates#1229]
Hello, was there a change I missed an announcement for? The type `secrecy::Secret<T>` no longer seems to exist. In its place I think I've found `SecretBox<T>`, `SecretString`, and `SecretStr`. Did I miss something? An upgrade broke my code from this.

**Comment by tony-iqlusion** [comment]
Yes, please read the CHANGELOG: https://github.com/iqlusioninc/crates/blob/main/secrecy/CHANGELOG.md#0100-2024-09-17
