### ISSUE TITLE
secrecy: cannot clone `SecretSlice`

### ISSUE THREAD

**Issue by tzilist** [iqlusioninc/crates#1233]
the new `SecretSlice` seems quite handly, however, with the recent changes to secrecy, there was removal of impl `CloneableSecret` on different array types (seemingly done [here](https://github.com/iqlusioninc/crates/pull/1140/files#diff-5d3f714040a9f8165af1e8ffcf211b6f01c0b838aafad9cd57f3ed8934389cc7L186-L202))

With that said, it is no longer possible to do something like `SecretSlice<u8>` as it now returns this error when attempting to implement clone

```
  --> iam/iam-api-key/src/model/api_key.rs:45:5
   |
39 | #[derive(Debug, Clone)]
   |                 ----- in this derive macro expansion
...
45 |     key: SecretSlice<u8>,
   |     ^^^^^^^^^^^^^^^^^^^^ the trait `secrecy::CloneableSecret` is not implemented for `[u8]`, which is required by `secrecy::SecretBox<[u8]>: std::clone::Clone`
   |
   = help: the following other types implement trait `secrecy::CloneableSecret`:
             model::api_key::KeyBytes
             model::api_key::encode::EncodedApiKey
   = note: required for `secrecy::SecretBox<[u8]>` to implement `std::clone::Clone`
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
   
  ```
  
  It is also not possible to do something like `SecretBox<[u8; 32]>` as it results in the same error.
  
  Would it be possible to add these implementations back into secrecy for basic array types like this?

**Comment by tzilist** [comment]
This looks like a duplicate of #1070

**Comment by tony-iqlusion** [comment]
Moving to this issue because `SecretVec` from #1070 is now gone, and `SecretSlice` is the new type
