### ISSUE TITLE
zeroize: support musl-libc

### ISSUE THREAD

**Issue by amrali** [iqlusioninc/crates#130]
Building tmkms under Alpine linux (3.8) fails because `linux::get_glibc_version` doesn't handle the version output of `ldd` for musl-libc.

What happens is that calling `ldd --version` is equivalent to `ldd` without any arguments, both output the version information and set the exit code to 1, which when wrongly checked by `linux::get_glibc_version` the package fails to build with a panic.

I don't think any other modifications are required to make zeroize work with musl-libc.

```
/ $ ldd
musl libc (x86_64)
Version 1.1.19
Dynamic Program Loader
Usage: ldd [options] [--] pathname

/ $ ldd --version
musl libc (x86_64)
Version 1.1.19
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```

**Comment by tarcieri** [comment]
@amrali can you confirm `zeroize` builds with `cargo build --no-default-features`?

**Comment by amrali** [comment]
it does work.

**Comment by amrali** [comment]
Closed by https://github.com/iqlusioninc/crates/pull/131
