### ISSUE TITLE
rpmlib: RPM reader API

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/crates#14]
This issue tracks the ability to read RPM package files. Presently no support is available.

Some reference information on the API is available here, courtesy the Fedora RPM Guide:

* **C API**: TBD
* **Python API**: https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch16s04.html

~~~Like #13, the file reader API depends on transaction sets, a binding for which is presently missing from **rpmlib-sys** because the bindgen tests are failing. Moving forward on this API will first require producing a safe binding to `rpmts.h` (#11).~~~

#11 is fixed, and #19 added transaction set support, so this is ready to work on for any interested takers.

**Comment by n3npq** [comment]
The easiest bindings are rpmInstall() and rpmErase() in lib/rpminstall.c, copying rust args into the needed structure. There are also similar interfaces for query/verify/sign available. All the tables for popt option processing are available for needed flags if you also bind libpopt.

If you want a lower level interface, use rpmReadPackageFile() which verifies package signatures.

I would avoid doing similar to Python interfaces which were mis-designed to accomodate "I don't want to verify signatures! I don't want to use a transaction!" politics from a long time ago.
