### ISSUE TITLE
zeroize: Provide ZeroizeOnDrop type

### ISSUE THREAD

**Issue by Shadlock0133** [iqlusioninc/crates#161]
Would it make sense to provide ZeroizeOnDrop wrapper type? Are there any security considerations with this design? Something like this:

```rust
pub struct ZeroizeOnDrop<T: Zeroize>(pub T);
impl<T: Zeroize> Drop for ZeroizeOnDrop<T> {
    fn drop(&mut self) {
        self.0.zeroize()
    }
}
```

**Comment by tarcieri** [comment]
I'm planning on adding this, but via a custom derive rather than a wrapper type.

**Comment by ebfull** [comment]
If you're trying to use someone else's struct from another library you won't be able to leverage a custom derive, so it still seems useful to have a `ZeroizeOnDrop` utility struct, though it comes at the cost of making the API larger for this library.

**Comment by tarcieri** [comment]
I think a `struct ZeroizeAThingOnDrop<T: Zeroize>(T)` would also be useful to have, however:

- I'd definitely like to support the custom derive, so we'd need names which clearly disambiguate `trait ZeroizeOnDrop` and `struct ZeroizeAThingOnDrop`
- This functionality is already provided by the [clear_on_drop](https://crates.io/crates/clear_on_drop) crate. Would it make more sense to submit a PR to that crate to use zeroize, so all existing users get the benefits of zeroize for free?

**Comment by tony-iqlusion** [comment]
Added `Zeroizing<Z>` in #182
