### ISSUE TITLE
Rename `ZeroizeWithDefault` to have the opposite implication

### ISSUE THREAD

**Issue by hdevalence** [iqlusioninc/crates#162]
This is a really minor nitpick, but I wonder whether it might be better to rename `ZeroizeWithDefault` to something like `DefaultIsZeroes`.

The reason is that "zeroize with default" makes it sound like the objects are wiped by replacing them with the default value (leaving open the possibility that it could be used with any type implementing `Default`), when AFAICT it's a marker trait saying that the default value for type is zeroes, and therefore zeroing the memory gives the same result as calling `default()`.

So naming the marker trait something like `DefaultIsZeroes` seems like it would be more clear for expressing the property attached to the marker trait, without making it sound like a trait that has some extra behaviour.

**Comment by tarcieri** [comment]
Seems reasonable to me. Submit a PR or I’ll try to get to it when i do the `Pin`-related changes

**Comment by tarcieri** [comment]
Done! The new trait name is `DefaultIsZeroes` as of #166, which I'll release shortly
