### ISSUE TITLE
zeroize_derive: Build fails on latest nightly

### ISSUE THREAD

**Issue by devashishdxt** [iqlusioninc/crates#172]
If you have following tuple struct:

```
#[derive(Zeroize, ZeroizeOnDrop)]
struct MyNum(u8);
```

The build fails with the following error: 
```
#[derive(Zeroize, ZeroizeOnDrop)]
         ^^^^^^^ invalid suffix `usize`
```

This may be because the generated implementation looks like this:
```
impl Zeroize for MyNum {
    fn zeroize(&mut self) {
        self.0usize.zeroize()
    }
}
```

**Possible reasons:**
Recently, this pull request was merged: https://github.com/rust-lang/rust/pull/59421 which introduced this regression: https://github.com/rust-lang/rust/issues/59553

**Playground:** https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1fdfb92bcacca661092abdce42cf8810

**Comment by tarcieri** [comment]
It seems I should've used `synstructure` to walk the fields of the struct. Not sure if that'd address this in particular, but I'd hope it would at least make it not-my-problem.

**Comment by tarcieri** [comment]
This should hopefully be fixed by the move to `synstructure`
