### ISSUE TITLE
zeroize: zero Vec capacity, not length

### ISSUE THREAD

**Issue by FauxFaux** [iqlusioninc/crates#178]
The [`Zeroize` implementation for `Vec`](https://github.com/iqlusioninc/crates/blob/8b47972e71a1931929306881fab33c6401878530/zeroize/src/lib.rs#L346) appears to zero out only the `len()`, not the `capacity()`.

I believe most people would probably expect the `capacity()` to be zero'd?

```
let mut v = Vec::new(); 
v.push(secret);
v.pop();
assert_eq!(0, v.len());
```
.. i.e. nothing is wiped here, and probably should be?

A possible implementation would be to `resize_with(Default::default())` the `Vec` before running the current implementation?

Spotted by @cuviper.

**Comment by tarcieri** [comment]
This is definitely a good idea. Will accept a PR, or otherwise add it myself.
