### ISSUE TITLE
zeroize: Yanking v0.8

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/crates#222]
`zeroize` v0.8 added an API with an implicit `Drop` handler when doing a `derive(Zeroize)`.

There are many cases where we'd like to be able to `derive(Zeroize)` without a drop handler, such as deriving it on `Copy` types what may wind up in a container that we'd like to zeroize, or for the new `Zeroizing` feature to clear temporary data on the stack.

For these reasons, v0.9 moved to a new `#[zeroize(drop)]` API which makes the derivation explicit. However, this is a potentially dangerous change if anyone is expecting to get one implicitly.

For this reason, I'd like to yank `zeroize` v0.8, and give people time to update to v0.9 which presently forces the selection of `#[zeroize(drop)]` vs `#[zeroize(no_drop)]`.

Once we're confident everyone who was previously using v0.8 has upgraded to v0.9 (say a couple weeks after it's yanked), we can make `#[zeroize(no_drop)]` an optional attribute, and eventually phase it out prior to a v1.0.

**Comment by tarcieri** [comment]
`zeroize` and `zeroize_derive` v0.8.0 have both been yanked.

Apologies for the disruption, but I feel this is needed to confidently move the API forward without endangering any existing users.

**Comment by tony-iqlusion** [comment]
`zeroize` and `zeroize_derive` v0.8.0 have both been yanked.

Apologies for the disruption, but I feel this is needed to confidently move the API forward without endangering any existing users.
