### ISSUE TITLE
Reserved `gcp` crate name

### ISSUE THREAD

**Issue by Hirevo** [iqlusioninc/crates#335]
Hello,
I am currently developing a library for interacting with the Google Cloud Platform services ([**repo is here**](https://github.com/Hirevo/gcp-rs)).  
I think it will soon be ready to publish on crates.io, so I looked up if the crate name **`gcp`** was free and I saw that the crate is already reserved since late 2018 and its "repository link" links here but there aren't any implementations for a **`gcp`** crate.  
So, I wondered whether you planned to use that crate name or if there is a possibility to trade the crate name ?

**Comment by tony-iqlusion** [comment]
Hi, thanks for asking!

We have one other person/group interested in the name, who have been working on a high-quality library they also soon intend to announce/publish. Failing everything else still might want to use it ourselves.

It looks like you've implemented a handful of services but are missing the core ones (e.g. IAM/OAuth) we feel are important for a core `gcp` crate.

We've also reserved/squatted crates for some of those services which we could maybe give you in lieu of an omnibus `gcp` crate, depending on circumstances, which might be a better starting place until you do have a solution for the core identity services.

**Comment by Hirevo** [comment]
Thanks for the response.  
No problem for keeping the name, my project is indeed still very much in development, so I've renamed it to **`google-cloud`** (that name was free on crates.io, so it's all good).  
Looking forward to seeing the library you are working on, then !
