### ISSUE TITLE
Documentation may be misleading WRT suggestion to use Pin to prevent accidental copies

### ISSUE THREAD

**Issue by bstrie** [iqlusioninc/crates#360]
The current zeroize crate documentation contains the following:

> ### Stack/Heap Zeroing Notes
>
>This crate can be used to zero values from either the stack or the heap.
>
>However, be aware several operations in Rust can unintentionally leave copies of data in memory. This includes but is not limited to:
>
> *    Moves and Copy
> *    Heap reallocation when using Vec and String
> *    Borrowers of a reference making copies of the data
>
>Pin can be leveraged in conjunction with this crate to ensure data kept on the stack isn't moved.

While it's strictly true that `Pin` can be used to this effect, I suggest that it's misleading as currently worded because this property only holds for types that are `!Unpin`, and therefore does not apply to the vast majority of types found in the wild. In particular the types that the zeroize crate implements `Zeroize` for, `Option`, `Vec`, and `String`, all implement `Unpin`, as does the `Secret` type from the secrecy crate.

I still think there might be merit in describing how `Pin` might be useful in conjunction with this crate, but it would probably take a more complete example to demonstrate how it could be done properly (which might be out of scope for the aforementioned document?).

**Comment by tony-iqlusion** [comment]
Thanks for the report. PRs accepted for an alternate wording. I think perhaps adding a phrase like "with due care" might be in order, potentially calling out `!Unpin`

**Comment by tony-iqlusion** [comment]
`zeroize` has moved to a new repository: https://github.com/RustCrypto/utils/tree/master/zeroize

If you feel this issue persists, please open a new issue in the new repository.
