### ISSUE TITLE
zeroize: Zero rand crate structures

### ISSUE THREAD

**Issue by timvisee** [iqlusioninc/crates#376]
I'm looking for support to _zero_ structures from the [`rand`](https://crates.io/crates/rand) crate. I'm wondering whether this is possible with the current API the crate provides.

I'd like this because I assume generated random numbers can be derived from the state the random number generator leaves in memory when it is dropped.

For example, I'd like to implement [`Zeroize`](https://docs.rs/zeroize/1.1.0/zeroize/trait.Zeroize.html) on this struct, but can't do this for [`Uniform`](https://docs.rs/rand/0.7.3/rand/distributions/struct.Uniform.html) and [`ThreadRng`](https://docs.rs/rand/0.7.3/rand/rngs/struct.ThreadRng.html):

https://github.com/timvisee/chbs/blob/d2adc73307f9c4598ee0c9c0f8891bc5854e5331/src/word.rs#L290-L299

Could support for something like this be implemented?

**Comment by tarcieri** [comment]
To do this, the `rand` crate types would need to impl `Zeroize`.

**Comment by timvisee** [comment]
Thought so. I guess that's a `wontfix` then. Thanks for the prompt response.

**Comment by tarcieri** [comment]
Yeah, there's not a lot `zeroize` or any other crate can do as it touches internal `rand` data structures.

I'd suggest filing an issue on the `rand` crate and see if they're open to supporting it.

**Comment by dhardy** [comment]
You mention `Uniform`, which does not store results (only the range and rejection zone), and `ThreadRng`, which is a `thread_local` value that is never destroyed, so in either case `Zeroize` is not going to be much use.

While this could potentially be applied to cryptographic PRNGs, the usual method of achieving this is with forward secrecy — which I'm sure @tarcieri can tell you more about than I can.
