### ISSUE TITLE
Some doc tests failing on build

### ISSUE THREAD

**Issue by nullr0ute** [iqlusioninc/crates#474]
When building zeroize some of the doc tests are failing when I'm building it on Fedora:

<pre>
   Doc-tests zeroize
     Running `/usr/bin/rustdoc --edition=2018 --crate-type lib --test /builddir/build/BUILD/zeroize-1.1.0/src/lib.rs --crate-name zeroize -L dependency=/builddir/build/BUILD/zeroize-1.1.0/target/release/deps -L dependency=/builddir/build/BUILD/zeroize-1.1.0/target/release/deps --cfg 'feature="alloc"' --cfg 'feature="default"' --extern zeroize=/builddir/build/BUILD/zeroize-1.1.0/target/release/deps/libzeroize-11008dc878dbf0c5.rlib`
running 4 tests
test src/lib.rs -  (line 75) ... FAILED
test src/lib.rs -  (line 86) ... FAILED
test src/lib.rs -  (line 33) ... ok
test src/lib.rs -  (line 100) ... ok
failures:
---- src/lib.rs -  (line 75) stdout ----
error: cannot find derive macro `Zeroize` in this scope
 --> src/lib.rs:79:10
  |
7 | #[derive(Zeroize)]
  |          ^^^^^^^
error: cannot find attribute `zeroize` in this scope
 --> src/lib.rs:80:3
  |
8 | #[zeroize(drop)]
  |   ^^^^^^^
error: aborting due to 2 previous errors
Couldn't compile the test.
---- src/lib.rs -  (line 86) stdout ----
error: cannot find derive macro `Zeroize` in this scope
 --> src/lib.rs:90:23
  |
7 | #[derive(Copy, Clone, Zeroize)]
  |                       ^^^^^^^
error: aborting due to previous error
Couldn't compile the test.
failures:
    src/lib.rs -  (line 75)
    src/lib.rs -  (line 86)
test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--doc'
</pre>

**Comment by tony-iqlusion** [comment]
This is because these tests require the `zeroize_derive` feature is enabled in order to pass.

However, I can add some feature-based gating to allow them to pass without that feature enabled, similar to this:

https://github.com/RustCrypto/AEADs/blob/master/aes-gcm/src/lib.rs#L68-L69
