### ISSUE TITLE
`impl From for Secret`

### ISSUE THREAD

**Issue by jhpratt** [iqlusioninc/crates#481]
Would a PR be accepted that adds the following implementation?

```rust
impl<T> From<T: Zeroize> T for Secret<T> {
    fn from(val: T) -> Self {
        Self::new(val)
    }
}
```

Without testing, I believe that's all the code that's necessary. It would allow simpler usage in some cases, namely methods that accept `Into<Secret<T>>`.

On an unrelated note, `fn new` in both `Secret` and `Zeroize` could trivially be `const`.

**Comment by tony-iqlusion** [comment]
> Would a PR be accepted that adds the following implementation?

Sure. Looks like you have a few syntax errors, but the idea is fine.

> On an unrelated note, fn new in both Secret and Zeroize could trivially be const.

That's true, but how is a `const` `Secret` useful?

**Comment by jhpratt** [comment]
Ok, I'll put together a PR later today.

For `const Secret`, obviously it wouldn't be series as it leaves scope, but even the ability to have it redacted in logs is quite nice.
