### ISSUE TITLE
zeroize: implement Zeroize for CString

### ISSUE THREAD

**Issue by robinkrahl** [iqlusioninc/crates#509]
I have to store a password that will be passed to a C API using the Rust FFI.  To avoid unnecessary copies, I store it as a `std::ffi::CString`.  But as `Zeroize` is not implemented for `CString`, I can’t wrap this field in a `Secret`.

Could you please add a `Zeroize` implementation for `CString`?

**Comment by tony-iqlusion** [comment]
I think this would be a good addition, yes.

**Comment by mso42** [comment]
Since `CString` is only in `std` (and not in `alloc`), I think this would have to be gated behind another crate feature?

**Comment by tony-iqlusion** [comment]
Yep, it would require a new `std` feature, which would need to be off-by-default.

**Comment by mso42** [comment]
Taking a look at this today, I think it might not be possible.

Rust's `CString` type "is a static guarantee that the underlying bytes contain no interior 0 bytes ("nul characters") and that the final byte is 0 ("nul terminator")" ([docs](https://doc.rust-lang.org/std/ffi/struct.CString.html)). Therefore overwriting interior bytes with 0s is explicitly breaking this guarantee. 

This might not prevent doing some kind of `SecretCString` type over in `secrecy` though, with a `Drop` implementation that does the zeroing immediately before free.

**Comment by mso42** [comment]
We could do something slightly wacky and overwrite internal bytes with `0xFF` or something, so as to obliterate the data while preserving the "no internal NUL bytes" guarantee.

**Comment by tony-iqlusion** [comment]
Moved to https://github.com/RustCrypto/utils/issues/650
