### ISSUE TITLE
zeroize: add a big fat warning that it's a low-level primitive

### ISSUE THREAD

**Issue by Shnatsel** [iqlusioninc/crates#533]
`zeroize` is a low-level crate and does not guard e.g. against implicitly copying the value. However, people sometimes assume that it does: https://benma.github.io/2020/10/16/rust-zeroize-move.html

While `secrecy` crate is recommended in the docs, it's buried below the sales pitch. Perhaps a big warning right at the top that `zeroize` is a low-level crate and most people should use `secrecy` instead would prevent such misunderstanding.

**Comment by benma** [comment]
Does `secrecy` really help here? I might have made a mistake, but in my test, the accidental moves are not prevented:

https://gist.github.com/benma/463ef5459bef29c7d47591c5c1cff906

**Comment by tony-iqlusion** [comment]
`zeroize` has moved to a new repository: https://github.com/RustCrypto/utils/tree/master/zeroize

If you feel this issue persists, please open a new issue in the new repository.
