### ISSUE TITLE
Consider adding an empty Zeroize trait implementation for core::marker::PhantomPinned

### ISSUE THREAD

**Issue by Allen-Webb** [iqlusioninc/crates#651]
Since often pinning is desired in conjunction with Zeroize, it would be nice to have zeroize define a Zeroize implementation for core::marker::PhantomPinned so that derive can be used with structs that contain PhantomPinned to prevent moving.

I can upload a pull request if it would help.

**Comment by tony-iqlusion** [comment]
Sounds good. It'd be great if you could open a PR.

**Comment by tony-iqlusion** [comment]
Moved to https://github.com/RustCrypto/utils/issues/651
