### ISSUE TITLE
Crate doesn't implement netconf

### ISSUE THREAD

**Issue by afpd** [iqlusioninc/crates#656]
https://crates.io/crates/netconf point to that repo, although it doesn't implement netconf 
additionally Doc link is pointing to Rick Astley

**Comment by tony-iqlusion** [comment]
Yes, it's true, we've "reserved" the names of several crates which have doc pages like this.

It seemed fun at the time but I agree they're confusing. Maybe it would make sense to yank the releases.

If you're interested in developing a netconf crate under the name, let me know.

**Comment by tony-iqlusion** [comment]
I've yanked the releases.
