### ISSUE TITLE
Zeroizing a `None` Option is not reliable

### ISSUE THREAD

**Issue by CodesInChaos** [iqlusioninc/crates#671]
Zeroize only safely erases data in an option if the option is `Some`. So if an option containing sensitive data gets set to `None` and then zeroized, this will not be a secure erasure.

Ideally zeroizing should work even for `None` options, but if that's not possible the readme should call out this pitfall.

**Comment by tony-iqlusion** [comment]
This should've been implemented in #649, although I haven't cut a release.

Is there some way in which you think that's inadequate, or do you just need a new release cut?

**Comment by CodesInChaos** [comment]
I'm talking about the case where the option is already `None` before `zeroize` is called. In that case zeroize is a no-op, while the inline memory of the option might still contain data.

Naively I'd expect that moving

                unsafe { ptr::write_volatile(self, Option::default()) }
                atomic_fence();

to after the `match(self)` would work.

(There might be another more subtle issue around uninitialized memory, but let's discuss that one separately)

**Comment by tony-iqlusion** [comment]
Aha, indeed, the wiping of the memory should be moved out from within the match statement.

If you'd like to open a PR to do that, great, otherwise I'll do it when I have some time.
