### ISSUE TITLE
is Anomaly support no_std feature? 

### ISSUE THREAD

**Issue by DaviRain-Su** [iqlusioninc/crates#693]
https://github.com/iqlusioninc/crates/blob/79a0a989bf17e1ca3253fb76691439b08029e1d5/anomaly/src/macros.rs#L18 
I find this Marco(format_err!) use format!, so I think this  crate is not support no_std.

I wish you reply.  
davirain

**Comment by tony-iqlusion** [comment]
Anomaly requires `std`.

Also note that we probably plan to phase it out now that there are better choices in the Rust ecosystem.

**Comment by DaviRain-Su** [comment]
> Anomaly requires `std`.
> 
> Also note that we probably plan to phase it out now that there are better choices in the Rust ecosystem.

Yes, can you advice for better choices for this crate.
