### ISSUE TITLE
zeroize: how to signal "safeness" to crate's users?

### ISSUE THREAD

**Issue by fjarri** [iqlusioninc/crates#757]
Person A creates a crate with a type that has some secret data inside, say, `SecretKey { inner: SecretDataType }`. They implement `Zeroize` and `Drop` (or `#[zeroize(drop)]`)  for `SecretDataType`, and stop at that - the secret data is now safe (to the extend Rust can guarantee it), the `drop()` of `SecretKey` will call the zeroizing `drop()` of `SecretDataType`, so there's no need to define anything for `SecretKey` itself.

Person B uses A's crate and wants to use `Secret<SecretKey>`. But they cannot, because `SecretKey` does not implement `Zeroize` - so they have to wrap it in a newtype and implement an empty `Zeroize` for it. And they still cannot assert in code that `SecretKey` keeps its secret - they have to rely on the docs. 

So what are the responsibilities of A here? Should they define an (empty) `Zeroize` for `SecretKey`? Should they export a `Secret<Box<SecretKey>>`? What's the convention?

I wonder if it would be more convenient to have a marker trait `ZeroizedOnDrop`, that A could implement for `SecretKey`, and `Secret` could require?

**Comment by tony-iqlusion** [comment]
It's a good question, and one I've encountered quite a bit. See also https://github.com/RustCrypto/AEADs/issues/65.

The biggest problem is types which want to maintain some kind of invariant which having a `Zeroize` impl would violate, and therefore *only* want be responsible for clearing internal fields via a `Drop` impl.

Indeed it would seem a marker trait like `ZeroizedOnDrop` would be helpful for this. I can potentially add one before the next release.

**Comment by tony-iqlusion** [comment]
Another interesting thing: this could be used with the custom derive support in lieu of the current (and somewhat awkward):

```
#[derive(Zeroize)]
#[zeroize(drop)]
```

Instead it could just be:

```
#[derive(ZeroizedOnDrop)]
```

And of course, `Zeroizing` would impl it.

**Comment by fjarri** [comment]
Oh, didn't realize you have two github accounts :)

As you may have guessed, I was asking this in relation to https://github.com/RustCrypto/traits/issues/671. Currently, if I want to wrap `SecretKey` in `Secret<Box>`, i have to do something like
```
struct SecretKeyInner(BackendSecretKey<CurveType>);

impl Zeroize for SecretKeyInner {
    fn zeroize(&mut self) {
        // BackendSecretKey is zeroized on drop, nothing to do
    }
}

impl Zeroize for Box<SecretKeyInner> {
    fn zeroize(&mut self) {
        // BackendSecretKey is zeroized on drop, nothing to do
    }
}

pub struct SecretKey(Secret<Box<BackendSecretKey<CurveType>>>);
```
because `Secret<T>` requires `T: Zeroize`, and there is no blanket impl for `Box<T> where T: Zeroize`.

**Comment by tony-iqlusion** [comment]
Moved to https://github.com/RustCrypto/utils/issues/652
