### ISSUE TITLE
Possible UB in `Zeroize` implementation for `Option<T>`

### ISSUE THREAD

**Issue by jessa0** [iqlusioninc/crates#782]
It seems the `Zeroize` implementation for `Option<T> where T: Zeroize` has language-level UB here:

https://github.com/iqlusioninc/crates/blob/f6deffcd0794528e041b12352bcd90e46583ce82/zeroize/src/lib.rs#L317

I believe, as a `repr(Rust)` enum, the memory layout and set of valid bit-patterns for `Option` is not defined, and that setting an enum's storage to an invalid bit-pattern while a reference to it exists, even if the value is never read, is instant language-level UB. The documentation for `Option` does mention guarantees for several special cases, but the `None` case still isn't defined for many of those cases, and the `Zeroize` implementation is more generic than that. [Here's an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a86270a4f0d74f55d1655a1d4a984f2b) of a miri error in such a situation, that scottmcm came up with on URLO [here](https://users.rust-lang.org/t/is-zeroing-a-repr-rust-enum-ub/61712/2).

**Comment by tony-iqlusion** [comment]
Thanks for reporting this. I was a bit hesitant about this in regard to PRs like #649 and #687, especially as I read ongoing discussion about `Option` padding like https://internals.rust-lang.org/t/allow-option-to-have-its-padding-explicitly-reused/14941

Unfortunately I don't have anything more to say about this topic, but can circulate this question among interested parties, particularly ones who work on unsafe code guidelines to get more feedback.

**Comment by jessa0** [comment]
FWIW, the language reference only [mentions](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html) wrt. invalid enum discriminants, "Producing an invalid value, even in private fields and locals. 'Producing' a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation." This to me, sounds like, despite an outstanding mutable reference, changing the underlying storage to an invalid value without reading it back through the reference is still defined. That same page in the reference of course mentions that the list of UB is not considered exhaustive, though.

**Comment by jessa0** [comment]
I found [this discussion] in the Unsafe Code Guidelines WG which seems to almost match this code. It might be worth bringing up whether `ptr::write_volatile` changes the equation at all.

**Comment by tony-iqlusion** [comment]
Moved to https://github.com/RustCrypto/utils/issues/653
