### ISSUE TITLE
zeroize 1.4.0 manifest problems

### ISSUE THREAD

**Issue by VeaaC** [iqlusioninc/crates#804]
When trying to use 1.4 as a dependency (which Cargo does automatically since it is considered a safe upgrade from 1.2), I get this error message:

```
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.0/Cargo.toml`
```

**Comment by tony-iqlusion** [comment]
Yep, MSRV is 1.51 now. Note that we're also using const generics: #794 

To support an older MSRV you'll need to pin to v1.3 for now, e.g. `zeroize = "=1.3"`

**Comment by VeaaC** [comment]
@tony-iqlusion thanks for pointing that out.

I guess I cannot rely on SemVer compatibility to make sure that I only get updates that compile in the same environment / do not break compilation (not even for my own crates, since their dependencies might have the same problem).
