### ISSUE TITLE
error: failed to download `zeroize v1.4.1` ... consider adding `cargo-features = ["resolver"]` to the manifest

### ISSUE THREAD

**Issue by ilmoi** [iqlusioninc/crates#816]
A bunch of projects on the solana blockchain that rely on `zeroize` broke because of a recent update.

Eg the examples in [anchor](https://github.com/project-serum/anchor) don't compile, and neither does [bonfida vesting](https://github.com/Bonfida/token-vesting).

The error we're getting is:
```
BPF SDK: /home/ubuntu/.local/share/solana/install/releases/1.7.6/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
error: failed to download `zeroize v1.4.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

Tried adding `cargo-features = ["resolver"]` to both `Cargo.toml` and `Xargo.toml`, with no luck.

Any advice on how to fix?

**Comment by guytbk** [comment]
@ilmoi 
Temp fix worked for me, until this is resolved would be to set:
zeroize = "1.3.0"
in your Cargo.toml file. It should force solana to use that version as well.

**Comment by tony-iqlusion** [comment]
The MSRV of `zeroize` 1.4 is Rust 1.51. Per our MSRV policy, we don't include this in our SemVer guarantees.

Pinning to 1.3 as suggested above should fix the problem.

See also: #804

**Comment by tony-iqlusion** [comment]
Note that this is also documented in the CHANGELOG:

https://github.com/iqlusioninc/crates/blob/main/zeroize/CHANGELOG.md#140-2021-07-18
