### ISSUE TITLE
zeroize: implement `Zeroize` for `PhantomData`

### ISSUE THREAD

**Issue by daxpedda** [iqlusioninc/crates#899]
Sometimes, when you want to implement `Zeroize` for a structure that contains a `PhantomData` field, it's necessary to implement `Zeroize` by hand. I suggest improving this by simply implementing `Zeroize` for `PhantomData`, which should be no-op, as this has no representation data wise I believe.

Alternatively, the derive proc-macro could detect `PhantomData` and skip it. I prefer the above solution though.

Willing to make the PR ofc!

**Comment by tony-iqlusion** [comment]
Moved to https://github.com/RustCrypto/utils/issues/651
