### ISSUE TITLE
Interest in path normalization?

### ISSUE THREAD

**Issue by sanmai-NL** [iqlusioninc/crates#94]
For our use cases we often want to normalize paths to be least likely to cause interoperability problems between platforms and applications. If a canonical path has to be normalized in this way, we deem it an non-interoperable path. In that case, we could then opt to fail early in some of our processes, e.g. in development pipelines.

For instance, some characters can be used in files on Linux, while they can’t on Windows (e.g., `\` or `|`). Some characters would better be substituted (e.g., spaces) to be compatible or usable with some applications (e.g., Unix shells). Some filenames are reserved on Windows (e.g., `CON`). Some paths would be too long on e.g. Windows. We may want to enforce decodability of the path in some text encoding (e.g. UTF-8), while that isn’t enforced in e.g. Linux.

We plan to make a small wrapper for `Path`s and `PathBuf`s as well to cover sanity checks along these lines.

Do we share this requirement somehow? If yes, does this fall under the scope of this crate? If yes, and then no, how could we cooperate to achieve optimal code reuse amongst us?

**Comment by tarcieri** [comment]
@sanmai-NL that's definitely an interesting project and requirement, but I'm not sure it's quite the same concern as what this project is trying to address.

This project is largely trying to address security issues that arise when absolute paths are not used, and avoid potential confusion that could cause an attacker-controlled program to be run with high privileges.

**Comment by tarcieri** [comment]
I'll go ahead and close this issue out for now, however please do let me know if you can think of ways we can collaborate
