### ISSUE TITLE
secrecy: Zeroize an serde_json::Value

### ISSUE THREAD

**Issue by simmel** [iqlusioninc/crates#978]
I see that you support serde by using my own struct but what if I just have a `serde_json::Value` like in this example https://docs.serde.rs/serde_json/#operating-on-untyped-json-values ?

I asked serde_json here serde-rs/json/issues/874 but they were unsure if it would work. I mean it's just a u8 Vec (?) somewhere it's just a matter of reaching it. (My code examples are also available in the linked issue)

Thank you!

**Comment by tony-iqlusion** [comment]
If the `alloc` features of secrecy/zeroize are enabled, it should be possible to zeroize a `Vec<u8>`.

You'll want to move it out of a `serde_json::Value` first into its own struct, or just operate on the raw `Vec<u8>`.
